PARENT_DATA_DIR = '/Users/pavlosh/Projects/kaggle/hpcontest/InitialTrainingSet/'

FLIGHT_HISTORY_COLS = [
    'flight_history_id',
    'airline_code',
    'airline_icao_code',
    'flight_number',
    'tail_number',
    'departure_airport_code',
    'departure_airport_icao_code',
    'arrival_airport_code',
    'arrival_airport_icao_code',
    'published_departure',
    'published_arrival',
    'scheduled_gate_departure',
    'actual_gate_departure',
    'scheduled_gate_arrival',
    'actual_gate_arrival',
    'scheduled_runway_departure',
    'actual_runway_departure',
    'scheduled_runway_arrival',
    'actual_runway_arrival',
    'creator_code',
    'scheduled_air_time',
    'scheduled_block_time',
    'departure_airport_timezone_offset',
    'arrival_airport_timezone_offset',
    'scheduled_aircraft_type',
    'actual_aircraft_type',
    'icao_aircraft_type_actual',]
